name: RefereeIQ
description: "RefereeIQ – Rugby’s Laws, Explained Like Never Before
  Meet Sofia, your AI rugby laws coach. She’s trained to understand the flow, nuance, and context of Rugby Union — so you can have real, back-and-forth conversations about the game’s most complex situations.

  Whether you’re a referee, player, coach, or fan, Sofia helps you:
  - Break down tricky laws and grey areas in plain language.
  - Explore “what if” scenarios and get context-driven answers.
  - See the game from a referee’s perspective to understand decisions on the field.

  Rugby is a game where the referee shapes the outcome more than in most sports. RefereeIQ gives you direct access to that perspective — anytime, anywhere."

publish_to: 'none'
version: 0.9.3+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  intl: ^0.18.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.0.18

  profanity_filter: ^2.0.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  image_picker: ^0.8.7
  firebase_storage: ^12.4.7
  flutter_markdown: ^0.7.7+1
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.4.0
  firebase_analytics: ^11.6.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sofia.png
    - assets/icons/google_icon.png
    - assets/icons/app_icon.png
    - .env
    - assets/laws/